services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pilot
      POSTGRES_PASSWORD: pilot
      POSTGRES_DB: pilot
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
