---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: back-minio
spec:
  encryptedData:
    accesskey: AgAKEmzcrkzpDtMNJ8JrLb0CjSBPFQnji1LZqDrjZH2z2ErwG6EpnpVrwZEI0oOR25UdwCul5GtuZSM5qARQerkBH+0fjM3tA0DqGDQ4gswxS/eG6bgMSqA6bhFfLeRNKKc0IbANKA39+oOTz04JT/b64b9XnPAKtrRke7ftgI5Q+Z7C/eV5B2s+5BeJbXBO7YQcv4ZQM/+k7WfPS/WLFxxel1eVuxxmWkPZ+YyirxHoQLsDodVDF2o5fG+np3d0hPXhhHmLYgx8H1w3Hd8sRPmezxmJ6P3X9T0f7a7h3udzJBkhcMZM9B3pBTA1NGd/cR7DSWVfAwS0sIQvMAxujFP/TecSVSMFlvCoJP6WWDiMBhPd7Ao+KsGyqKWGggDEx1F/3/7M+QQWQyqpS8nEHojW7KlsVkHr6m/tt7VL/Fgnm8ODEZzOb3CJWLjvJ9c3vEL+9xNcEotg33UUb0xyXVruUSw+SgYHy8ZIlOfGRSjee6w/aCg2a/H1Y2oXg8WXYJvLps3Ht4R/wAPJKwzq4pgQN/KC8xXCUSii/uthAep8Aknk62tiDWIVqeVHs6DKopIlo1C/OIfvkULVDTbGmv5ZKTJ1RrJLFDihL60kJtIzP5SS9sZ+mD3EXlIC+C+RSx/gtUd2XCMqg9qogLEwn4J7NgFa18YasGQwL3S8TKdHXY/avNXykgzdxLDN8/Z2b8d4GDcl7bEehyARODEnHxGb5KZI6UwNTNHzGf1oBYrhU19RAK4=
    secretkey: AgCB1Ueo3dSnDPcOjRuXA3Tl5c40wyk1i2Lh2rCb6vWQdhgzdatfG60wM/cWWjvioF32lLofuaHbeSkJApUbl4n8WbVUY8xNptXzUJOIeTDtrLaimzDezBc99WVbxM06BKjK4DqPRyhqoYXVQsMVYo99BiuyGvof/unJUbRkfEGsMTMzR2tVwSDdPGJ471M0e30vrEry/mkcdeYfQ/zTar12M3EkuISKoccrFH2yQfMV7yDBaIX6mOualxcW17dI6nPmuOy21+W8iJI31+7WdVuO8a4LVh1UE6OSUiiHesEuFP+UjN/S8TwsV3N96NZOOXkEKvy7/1VWlY3QNhyCl9e8Youbxbyd5nMXByrL7wwdDnHxbz3cJ4vywoWCYzztgTG7ZOu4hxDQz8mh5yz6QprbkQIMPjJghuHVJgFKhAIPYGS65iq6uifFUN45Dpk19/PYC0ebkWPxYErDAZWASpUuPMQDd4pDA7kuMVio1wE8gaTiXRz81dECEYA6CYKALFqm/nNW01heMcwrBc1dvCHCqIQLsFBViBq5TrBS6dAgAQHotsJyMMan69cQZ4f1i+l0WcUAM9XV07LDeLnKZDZwApjD5gf0gHmRR3DF3BNjfaKUAqxXqAuCdsYJwQW8B/sVDvfGEZDUsolrjd8TM5SPx9y9zt7i3OvhT4P6xfzMVG4E1vOoj6pTTI0R1uDrPAriJLhTxoTk21FrGZcOOP/+iMzQiErKagih64AX/3rNyXrggFY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: back-minio
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: back-postgresql
spec:
  encryptedData:
    postgres-password: AgB3xDvOtsqY4gfn9bwYCjOUbTUV0qsXBkhC2FVUwM+cnuZSaTxvcFqsoQ3hS2nbem3nKi1jF3HZSCJ1ndmm38J26nzeOvYmJ0Xtcug6qYeiPhymij9D0bgx0nO3rlMav037YvmWVyI0z8t76GSe7Xx6wNB67MRjy9M/N6O8RaHctDY5WcKCEjam4KVOPMFJq1xD7Ghflrsvdvy05c1+L+DI3THcnoVDoZn2v+Wp56MmsgUHLY1hgZEnoeMrGSheabJTN0T3iViZ6ECEU/BUsM0ARW5KCqhDhSJGk4108yXJayzv7n6XgK8Fm5cSiRVVXBUEtqFuC/0fYpfoPMUlZ1+GwN6ZIwyKCmwq8kKpwf8BeQxxr7/qwf+SAd1AN/kOgBdInoecq269jFKBACl0Cu+DyXx4JC+DyTo5/E1jziwAhmC7A+By96d+nxOvX3aOjW5Gm6ItazhqcFsdQHbQa6WIs1enNi6BjT8AUeaviLI9EuZQg3ftQ00efFjSw0snu+6vX/eb9HgovsK5OjoZ0btFGBJrCwJslr2bhlwZW4krVblRBcEPoCCWBF88A7eFDF+q0fqHmP9+RsCBFgpW58atq56aI9LlxiawJGuN/Dwhr+7+n9nKKSQL+zGYDBmksfLEwWLJ9FM1CqeCenmfOgRfPh1iMzmoSSV/y3yzG+lIKam7TahLXchCej0zA1x+j5fJcDhE11wZemY9i10=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: back-postgresql
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: back-jwt
spec:
  encryptedData:
    access: AgBzZToZV3jd8Ux40gSXFcHb82x3xFYiVblChE3muTCihiraM0d2iCsCFy2d0Hz3yszN+DRYwXjMyFLLQupiWwpBLagGmqKugMP3pEJk5egiVbJ63K1rjLFBFd+BufbgoNRdLuodNFzc2Jy1xwRwe9hd6iCG2I/eBh6UMuVd1w689J0//eXISKCtCNhS1kFHnYHIcPbqtYr3IL/e3tvXOyD93dn4hwjtRDnjjjY8G1E2J1IKvAlm+Fy26N9RlG/hOVuZ9pMtVXFHIxGBWL4KesCiLv8iJdHLU/Ordu1tos5js8BhJNyiYG+2LYekCji1BAcHtq7AL2aFOyS9H/fhhs1e3uIF9R1E6JGIajvfkzbwNePFAF9q3+VwaFmCZSW1Ybnfnv2CLvRsdPOg+j/icKIqZ7epjqH7O5rn+t2CyLOKCj08HVq6lfpXsWNJlPl7TLWtsZ+vhXqCOwx7aGIimwHC5SvYSM+AUqUYAWvVz03iS/RQ3MfFcWbVaK94YS+7UuKNMuCmWY+GPgLZPWCZ6yiIF7M1wk2DDzXfChTPHjuC2GnnQERsvr6UYVaO8XtrmBEyiBtoMHBux8zq5dj6MrZt80aYRwBz+CbJafhFObHshewh0CGpRrhDTSexuV6UPN0BEY8bUFw7tc3ulfH26+1yStmXn2f6n0hhciCixNtZ+6qNkY/H8og6mcczLYtecAXZOlFS7hjjpeN8VqL6QyboqY4mJBp1vMXWuHCweo4QPhfj3kg9aqejYxEtyzsg5YX+N6J+WWmp2xWZNqAFeGwq
    refresh: AgA7urTY9Ggl09qPwGJoXfnv3KonnRh8QCYbT0jjI3Hoq+NdbykxBiUAzvL8xX8pxIRNjHymcKlIBqAxJ8DBM5JLUb7Vi+6dIfTI4HrMG/MN7ORDKT9nOrYWRXLCbdiFOvWhjcjbDWhHAq8bsQY4SNDlUVMhf3qgeMogG1clAX6RbsXNR3RF2BLmjqHhFr92LfQBDD0AntkrzA1Y7vqSsMyFYTH8zO5TjyJfLN6nfEZU3sxdIS8EY8KUrkepldVRgONX8CLUjJyfRk4m9UlpW7nwsm3fvXFIPIWjxzlZwbs/kVLCkpo4js23TzzrkSGPk1b3Zl+tjxywxauqjJxKXvi5yX0XMU0izQIuFchqLfphZfw6GHy0ElWmEbNl1r8tcSNSHMqMKTpL62mJQQ8/+Gs8oT+8A6ZnPr4+Vr+JKWo9C62m7ircvn6DEi6YxyS4OG0vCMJ4KeD9Q8lWar/+yJjGhb/AWv4EMhOlLiqzDnbPsdBn8ME8Od2uXw1XGQl+dGzmtOJnn0u/TDedlf8mlXFdWhq26o9MpLwYQwoG8r7/9XoPUhN9NcE0gVVDyk64pbPiaZgq+nHBRqrUUky2Arc8impAlGHizBHaBItyBxjTj8dj+hYqDmq+mJPlYfbnqZE0zgjxYrwkqidux5VywT+tzGovbfdCsZU7ocCpuaH+aZ/GEHWoKlauoqHOjyqyM4qslkwXNoN5gy0Ldr2Ew6QqFUlLVGm6X81+Jvleb56UBfigi2OTC6j6YzT4UmbtArbRkOm41FeFRmokNmIyY+gL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: back-jwt
    type: Opaque
