name: Build All Images

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      packages: write
    name: Build All Images
    strategy:
      matrix:
        inputs:
          - image_name: "pilot-image-board-back"
            dockerfile_path: "back/Dockerfile"
            context: "back"
          - image_name: "pilot-image-board-back-migration"
            dockerfile_path: "back/prisma/Dockerfile"
            context: "back"
          - image_name: "pilot-image-board-front"
            dockerfile_path: "front/Dockerfile"
            context: "front"
    uses: mmoreiradj/pilot-image-board/.github/workflows/build-docker-image.yaml@main
    with:
      image_name: ${{ matrix.inputs.image_name }}
      dockerfile_path: ${{ matrix.inputs.dockerfile_path }}
      context: ${{ matrix.inputs.context }}
    secrets: inherit
