name: Clean Up Argo App and Namespace

on:
  workflow_call:
    inputs:
      namespace:
        description: "Namespace to clean up"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to clean up"
        required: true
        type: string

jobs:
  clean-up:
    name: Clean Up
    runs-on: ubuntu-latest
    steps:
      - name: Setup Argo CD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
      - name: Login to ArgoCD
        run: argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD"
      - name: Delete Argo App
        run: argocd app delete --grpc-web --yes --selector "target-ns=${{ inputs.namespace }}"
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
      - name: Setup Kubeconfig
        run: |
          echo "$KUBECONFIG" > /tmp/kubeconfig
          chmod 600 /tmp/kubeconfig
      - name: Delete Namespace
        run: KUBECONFIG=/tmp/kubeconfig kubectl delete ns "${{ inputs.namespace }}"
