name: Clean Up Argo App and Namespace

on:
  pull_request:
    types: [closed]

jobs:
  clean-up:
    name: Clean Up
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform Backend
        working-directory: ./.infra/terraform
        run: |
          echo "$EPHEMERAL_TF_BACKEND" > /tmp/backend.tf
          echo "key = \"kubernetes/apps/${{ github.repository }}/ephemeral/pr-$PR_NUMBER/terraform.tfstate\"" >> /tmp/backend.tf
          chmod 200 /tmp/backend.tf
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
      - name: Setup Kubeconfig
        run: |
          echo "$KUBECONFIG" > /tmp/kubeconfig
          chmod 600 /tmp/kubeconfig
      - name: Terraform Init
        working-directory: ./.infra/terraform/ephemeral
        run: terraform init -backend-config=/tmp/backend.tf
      - name: Terraform Destroy
        working-directory: ./.infra/terraform/ephemeral
        id: tf-apply
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | sed 's/.*\///g')
          NAMESPACE=$(echo $REPO_NAME | sed 's/\//-/g')-pr-$PR_NUMBER
          terraform destroy \
            -auto-approve \
            -var "vault_token=$VAULT_TOKEN" \
            -var "vault_address=$VAULT_ADDR" \
            -var "namespace=$NAMESPACE" \
            -var "image_tags=$COMMIT_SHA" \
            -var "charts_target_revision=${{ github.head_ref }}" \
            -var "kube_config_path=/tmp/kubeconfig"
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :white_check_mark: Cleaned up ephemeral deployment !

            :wave: Thanks for introducing bugs to the codebase!
