name: Clean Up Argo App and Namespace

on:
  pull_request:
    types: [closed]

jobs:
  clean-up:
    concurrency:
      group: ephemeral-${{ github.event.pull_request.number }}
    name: Clean Up
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > "${{ runner.temp }}/kubeconfig"
          chmod 400 "${{ runner.temp }}/kubeconfig"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform Init
        working-directory: .infra/terraform/ephemeral
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
            -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}" \
            -backend-config="region=${{ secrets.S3_REGION }}" \
            -backend-config="key=kubernetes/apps/${{ env.GITHUB_REPOSITORY }}/ephemeral/pr-${{ env.PR_NUMBER }}/terraform.tfstate" \
            -backend-config='endpoints={"s3": "${{ secrets.S3_ENDPOINT }}"}'
      - name: Terraform Destroy
        working-directory: ./.infra/terraform/ephemeral
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | sed 's/.*\///g')
          NAMESPACE=$(echo "$REPO_NAME" | sed 's/\//-/g')-pr-"$PR_NUMBER"
          terraform destroy \
            -auto-approve \
            -var "vault_token=${{ secrets.VAULT_TOKEN }}" \
            -var "vault_address=${{ secrets.VAULT_ADDRESS }}" \
            -var "namespace=$NAMESPACE" \
            -var "image_tags=$COMMIT_SHA" \
            -var "charts_target_revision=${{ github.head_ref }}" \
            -var "kube_config_path=${{ runner.temp }}/kubeconfig"
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :white_check_mark: Cleaned up ephemeral deployment !

            :wave: Thanks for introducing bugs to the codebase!
