name: Pull Request

on:
  pull_request:

jobs:
  create-application:
    name: Create ArgoCD Application
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - name: Say Hello
        run: echo "${{ github.actor }}"
#   qa:
#     name: Quality Assurance
#     strategy:
#       matrix:
#         working-directory: [back, front]
#     uses: mmoreiradj/pilot-image-board/.github/workflows/run-checks.yaml@main
#     with:
#       working-directory: ${{ matrix.working-directory }}

#   build:
#     needs: [qa]
#     name: Build
#     uses: mmoreiradj/pilot-image-board/.github/workflows/build-all-images.yaml@main
#     permissions:
#       packages: write

#   # Tells the user that the images were built successfully
#   comment-build:
#     permissions:
#       pull-requests: write
#     name: Output Built Images
#     runs-on: ubuntu-latest
#     needs:
#       - build
#     steps:
#       - name: Comment Pull Request
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           message: |
#             :rocket: The images were built successfully!

#             :white_check_mark: Frontend image: `docker pull ghcr.io/${{ github.repository }}-front:${{ github.event.pull_request.head.sha }}`
#             :white_check_mark: Backend image: `docker pull ghcr.io/${{ github.repository }}-back:${{ github.event.pull_request.head.sha }}`
#             :white_check_mark: Backend migration image: `docker pull ghcr.io/${{ github.repository }}-back-migration:${{ github.event.pull_request.head.sha }}`
