name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    uses: mmoreiradj/pilot-image-board/.github/workflows/build-all-images.yaml@main
    permissions:
      packages: write
