name: test-ci

on:
  push:

jobs:
  clean-up:
    name: Clean Up
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: 2
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform Init
        working-directory: .infra/terraform/ephemeral
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
            -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}" \
            -backend-config="region=${{ secrets.S3_REGION }}" \
            -backend-config="key=kubernetes/apps/${{ env.GITHUB_REPOSITORY }}/ephemeral/pr-${{ env.PR_NUMBER }}/terraform.tfstate" \
            -backend-config='endpoints={"s3": "${{ secrets.S3_ENDPOINT }}"}'
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
